-- Client Interaction CRM initial schema
-- Deployment model: one Supabase project = one trusted team.

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(btrim(name)) between 1 and 200),
  form text,
  inn text,
  contact_person text,
  address text,
  website text,
  phone text,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid() references auth.users(id) on delete set null
);

create table if not exists public.calls (
  id bigint generated by default as identity primary key,
  call_date date not null default current_date,
  description text not null check (char_length(btrim(description)) between 1 and 5000),
  client_id bigint not null references public.clients(id) on delete cascade,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid() references auth.users(id) on delete set null,
  created_by_email text
);

create index if not exists clients_name_lower_idx on public.clients (lower(name));
create index if not exists clients_created_by_idx on public.clients (created_by);
create index if not exists calls_client_id_idx on public.calls (client_id);
create index if not exists calls_call_date_idx on public.calls (call_date desc);
create index if not exists calls_created_by_idx on public.calls (created_by);

-- Attribution is assigned by the database, never trusted from browser input.
create or replace function public.stamp_client_creator()
returns trigger
language plpgsql
set search_path = public, auth
as $$
begin
  if tg_op = 'INSERT' then
    new.created_by := auth.uid();
  else
    new.created_by := old.created_by;
  end if;
  return new;
end;
$$;

create or replace function public.stamp_call_creator()
returns trigger
language plpgsql
set search_path = public, auth
as $$
begin
  if tg_op = 'INSERT' then
    new.created_by := auth.uid();
    new.created_by_email := nullif(auth.jwt() ->> 'email', '');
  else
    new.created_by := old.created_by;
    new.created_by_email := old.created_by_email;
  end if;
  return new;
end;
$$;

drop trigger if exists clients_stamp_creator on public.clients;
create trigger clients_stamp_creator
before insert or update on public.clients
for each row execute function public.stamp_client_creator();

drop trigger if exists calls_stamp_creator on public.calls;
create trigger calls_stamp_creator
before insert or update on public.calls
for each row execute function public.stamp_call_creator();

alter table public.clients enable row level security;
alter table public.calls enable row level security;

-- Supabase may grant public-schema privileges by default. Remove anonymous
-- table access explicitly; RLS remains the primary row-level security boundary.
revoke all on table public.clients from anon;
revoke all on table public.calls from anon;

grant select, insert, update, delete on table public.clients to authenticated;
grant select, insert, update, delete on table public.calls to authenticated;

grant usage, select on sequence public.clients_id_seq, public.calls_id_seq to authenticated;
revoke all on sequence public.clients_id_seq, public.calls_id_seq from anon;

drop policy if exists "team can read clients" on public.clients;
create policy "team can read clients"
on public.clients for select
to authenticated
using (true);

drop policy if exists "team can create clients" on public.clients;
create policy "team can create clients"
on public.clients for insert
to authenticated
with check (created_by = auth.uid());

drop policy if exists "team can update clients" on public.clients;
create policy "team can update clients"
on public.clients for update
to authenticated
using (true)
with check (true);

drop policy if exists "team can delete clients" on public.clients;
create policy "team can delete clients"
on public.clients for delete
to authenticated
using (true);

drop policy if exists "team can read calls" on public.calls;
create policy "team can read calls"
on public.calls for select
to authenticated
using (true);

drop policy if exists "team can create calls" on public.calls;
create policy "team can create calls"
on public.calls for insert
to authenticated
with check (created_by = auth.uid());

drop policy if exists "team can update calls" on public.calls;
create policy "team can update calls"
on public.calls for update
to authenticated
using (true)
with check (true);

drop policy if exists "team can delete calls" on public.calls;
create policy "team can delete calls"
on public.calls for delete
to authenticated
using (true);
